GCP MySQL: remove authorized_network parameter
pivotal-cf/docs-csb-gcp pull request #43
Opened 2022-12-19 12:46 UTC by zucchinidev

[#183975388](https://www.pivotaltracker.com/story/show/183975388)

Which other branches should this be merged with (if any)?

None

2022-12-19 13:36 UTC, jhvhs requested changes

2022-12-19 13:36 UTC, jhvhs commented on upgrading.html.md.erb
> +you must change the configuration.
**suggestion**: We should tell that the configuration change must happen before starting the upgrade. We should also mention that the same applies to the instances with a user-supplied `authorized_network`. And that all the instances with the attribute left in place will not be manageable after the upgrade.

2022-12-21 11:47 UTC, pivotal-marcela-campo commented on upgrading.html.md.erb
> +you must change the configuration.
Good point about instances that have the value already specified. The bad thing is that these attributes are not updateable, so they won't be able to update any of them. I'll make a note for it in the docs and double check with Piyali we are ok with this.

2022-12-21 14:46 UTC, jhvhs commented on reference/gcp-mysql.html.md.erb
> +        where the `https://www.googleapis.com/compute/v1/` prefix can be omitted.
**question**: Do we want to mention that this must be the same network PCF compute VMs run on?

2022-12-21 14:48 UTC, jhvhs commented on upgrading.html.md.erb
> +See [Set `authorized_network_id` for the MySQL service](gcp-mysql-authorized-network-id) if you have the `authorized_network` property  specified in a custom plan.
Missing `#` in the anchor. (#gcp-mysql...)

2023-01-03 10:15 UTC, merged

2023-01-03 10:16 UTC, RichardJJG commented
I've merged this to prevent mounting merge conflicts with other queued PRs for these docs. If further changes are wanted, please raise a new PR.